[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/capture",
    "crates/overlay",
    "crates/cli",
    "crates/ocr",
    "crates/source",
    "crates/layout",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
rust-version = "1.77"
license = "Apache-2.0"
repository = "https://github.com/semishnikov/DynoTranslate"

[workspace.dependencies]
lumen-core = { path = "crates/core" }
lumen-capture = { path = "crates/capture" }
lumen-overlay = { path = "crates/overlay" }
lumen-ocr = { path = "crates/ocr" }
lumen-source = { path = "crates/source" }
lumen-layout = { path = "crates/layout" }
png = "0.17"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[profile.release]
lto = "thin"
codegen-units = 1
strip = "symbols"
